### ISSUE TITLE
Add github repo link to the webpage?

### ISSUE THREAD

**Issue by MartinKjunior** [OSIPI/OSIPI_CAPLEX#35]
Should we add a link to the github repo if that's how the website is to be updated by others?

**Comment by MRdep** [comment]
Should be there already on the first page....




--------------------------------------------------------------------------
Ben Dickie, PhD
Senior Experimental Officer and Senior Research Fellow in Preclinical MRI
7T MRI laboratory, G727
Stopford Building
The University of Manchester
mob: 07837837807 | e: ***@***.***
------------------------------------------------------------------
________________________________
From: MartinKjunior ***@***.***>
Sent: 11 October 2023 16:15
To: OSIPI/OSIPI_CAPLEX ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [OSIPI/OSIPI_CAPLEX] Add github repo link to the webpage? (Issue #35)


Should we add a link to the github repo if that's how the website is to be updated by others?

**Comment by MartinKjunior** [comment]
Ah, it's written as a link, but mkdocs-material has the option to add a nice ribbon on top of the page accessible at all time throughout the website.
![image](https://github.com/OSIPI/OSIPI_CAPLEX/assets/87950285/5c42672d-1162-44db-bdf2-1510e2fc286b)
What do you think?

**Comment by MartinKjunior** [comment]
Added in the pull request
