### ISSUE TITLE
Suggestion: Invert OSIPI logo text to white

### ISSUE THREAD

**Issue by MartinKjunior** [OSIPI/OSIPI_CAPLEX#54]
The top bar is dark blue and `OSIPI_logo.png` text is black which doesn't stand out well. Consider changing text colour to something lighter (e.g. white) to make it legible.
![image](https://github.com/OSIPI/OSIPI_CAPLEX/assets/87950285/952612e5-69a3-428f-877a-479596c1cd07)

**Comment by Aditish51** [comment]
Hello, This is Aditi. Can you assign this issue to me?

**Comment by MartinKjunior** [comment]
@MRdep I've added this issue because I thought the logo being white would be more visible (ties in with #62 ). If it's okay to change the black text into white, please give Aditi the assignment.

**Comment by MRdep** [comment]
> Hello, This is Aditi. Can you assign this issue to me?

Hi Aditi, thanks for contributing. Feel free to tackle any of the other open issues.

**Comment by Aditish51** [comment]
Hi @MRdep Thanks for assigning me this issue.I think it is looking better now.

![Uploading Screenshot from 2024-03-08 18-26-34.png…]()

**Comment by MartinKjunior** [comment]
@Aditish51 Could you please check if the colour of the new text is purely white?

**Comment by Aditish51** [comment]
Hey @MartinKjunior here is the image .I think since it is small maybe that is why it looks faded else if you want I can correct it once again.
![OSIPI_logo](https://github.com/OSIPI/OSIPI_CAPLEX/assets/150245832/9662793b-5ca8-4f47-9e54-c0ff648a1dfc)
