### ISSUE TITLE
Suggestion: add a social card

### ISSUE THREAD

**Issue by MartinKjunior** [OSIPI/OSIPI_CAPLEX#57]
When you link to a website in most modern chats, you can see a preview of the website. The image in the preview is the social card which we could add as the mkdocs material supports it https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/ . A tutorial on how to make a custom social card https://www.youtube.com/watch?v=4OjnOc6ftJ8 . Would be good to have someone design it to OSIPI's liking. Unfortunately mkdocs-material only allows sponsors to use the built-in tools for custom social cards, so we would need to design our own and then figure out how to use the open graph protocol to add it in.

**Comment by Aditish51** [comment]
@MartinKjunior Can I work upon it? If it a part of someone's PR then please tell me any of the issues which I can try. I would love to work upon some more issues.

**Comment by MartinKjunior** [comment]
> @MartinKjunior Can I work upon it? If it a part of someone's PR then please tell me any of the issues which I can try. I would love to work upon some more issues.

I think this is open. Go for it!

**Comment by Aditish51** [comment]
@MartinKjunior I just used Canva to create this social card for "how to contribute?" and then added the meta tag in the contribution.md file. But since I have build the site locally so I am not able to figure out how to verify that whether social card with the link is working or not?

**Comment by MartinKjunior** [comment]
> @MartinKjunior I just used Canva to create this social card for "how to contribute?" But since I have build the site locally so I am not able to figure out how to verify that whether social card with the link is working or not? Please help me with this. ![Contribution Tutorial](https://private-user-images.githubusercontent.com/150245832/311445997-aacfb37c-2fef-4a55-a01d-7be03f05e784.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNTcxOTksIm5iZiI6MTcxMDE1Njg5OSwicGF0aCI6Ii8xNTAyNDU4MzIvMzExNDQ1OTk3LWFhY2ZiMzdjLTJmZWYtNGE1NS1hMDFkLTdiZTAzZjA1ZTc4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQxMTM0NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMDlhYmQ2ZWM1NWUwN2FmMzcwMjI0NzUyODEwM2VlZGY5ZTIwNDNjN2NmNWRmY2JiM2JjZWM2YzNmM2RjMzYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.q-nZUTA-IAAJCUj02i9FIm37gP2E4jVbxfbiKRNuJcQ)

Try [this plugin](https://stackoverflow.com/questions/58748838/how-to-test-sharing-social-media-link-preview-on-local-environment) perhaps? I have not worked on creating the social card so can't help much there, sorry.
