### ISSUE TITLE
Add email for change proposals

### ISSUE THREAD

**Issue by MartinKjunior** [OSIPI/OSIPI_CAPLEX#61]
In the tutorial page add links to people's emails where users can send proposed changes.

**Comment by Aditish51** [comment]
@MartinKjunior I would like to give it a try. Please assign this to me.

**Comment by MartinKjunior** [comment]
> @MartinKjunior I would like to give it a try. Please assign this to me.

Hi Aditis, this is already part of my pull request, so it just needs to get accepted. Sorry about that.

**Comment by MartinKjunior** [comment]
Completed as part of #65
