### ISSUE TITLE
Inconcistencies in the way tracer kinetic models are abbreviated. 

### ISSUE THREAD

**Issue by MRdep** [OSIPI/OSIPI_CAPLEX#73]
Ensure consistency of naming, such as Linear and stationary system model should be LSSM not LSS model

**Comment by Aditish51** [comment]
Hello, If this issue is just  for naming. Can I work on it?

**Comment by MRdep** [comment]
Yes, please do. You will need to edit the relevant model .mk file. Please create a fork of the repo, work on your local version, then submit a pull request for review. If you also want to try to translate the remaining indicator kinetic models from here https://docs.google.com/document/d/1v4PEGxHt9qg3pbvt2BcX6m8q6RyyIu7CrN1b3xreURE/edit that would be really helpful too.

Thanks,

Ben





--------------------------------------------------------------------------
Ben Dickie, PhD
Senior Experimental Officer and Senior Research Fellow in Preclinical MRI
7T MRI laboratory, G727
Stopford Building
The University of Manchester
mob: 07837837807 | e: ***@***.***
------------------------------------------------------------------
________________________________

**Comment by MRdep** [comment]
Hi @Aditish51,

Yes that's exactly right. So it would be LSSM and 1CNEXM. 

If you are able to transfer the remaining model definitions from the Google Doc, that would be ace.

Thanks,

Ben
